# @format

version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      # external port : internal port
      - ${POSTGRES_PORT}:5432
    # volumes:
    #   - data_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - data_rabbitmq:/var/lib/rabbitmq/

volumes:
  # data_pg:
  data_rabbitmq:

networks:
  postgres:
    driver: bridge
