# Generated by Django 5.1.4 on 2025-02-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="children",
            new_name="root",
        ),
    ]
