# Generated by Django 5.1.4 on 2025-01-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="custompermissions",
            old_name="create",
            new_name="can_create",
        ),
        migrations.RenameField(
            model_name="custompermissions",
            old_name="delete",
            new_name="can_delete",
        ),
        migrations.RenameField(
            model_name="custompermissions",
            old_name="read",
            new_name="can_read",
        ),
        migrations.RenameField(
            model_name="custompermissions",
            old_name="update",
            new_name="can_update",
        ),
    ]
