# Generated by Django 5.1.4 on 2025-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customgroup_created_customgroup_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="customgroup",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
