# Generated by Django 5.1.4 on 2025-03-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customgroup_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="default_group",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="is admin"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="is staff"),
        ),
    ]
