# Generated by Django 5.1.4 on 2025-02-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kits", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kit",
            old_name="title",
            new_name="name",
        ),
    ]
