# Generated by Django 5.1.4 on 2025-02-04 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kits", "0002_rename_title_kit_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("inherit_permissions", models.BooleanField(default=True)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="folder",
            options={"ordering": ["updated"]},
        ),
        migrations.AlterModelOptions(
            name="kit",
            options={"ordering": ["updated"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["updated"]},
        ),
    ]
