// This file is auto-generated by @hey-api/openapi-ts

export type Answer = {
    readonly id: string;
    readonly updated: string;
    updated_by: CustomUser;
    readonly tags: Array<string>;
    readonly created: string;
    inherit_permissions?: boolean;
    title: string;
    description?: string;
    image?: string | null;
    index?: number;
    readonly polymorphic_ctype: number | null;
    parent?: string | null;
};

export type AnswerRequest = {
    inherit_permissions?: boolean;
    title: string;
    description?: string;
    image?: string | null;
    index?: number;
    parent?: string | null;
};

/**
 * A ModelSerializer that takes an additional `fields` argument that
 * controls which fields should be displayed.
 */
export type CustomUser = {
    readonly id: string;
    email: string;
    avatar?: string | null;
    first_name?: string;
    last_name?: string;
    is_active?: boolean;
    readonly groups: Array<Nested>;
};

/**
 * A ModelSerializer that takes an additional `fields` argument that
 * controls which fields should be displayed.
 */
export type CustomUserRequest = {
    email: string;
    avatar?: (Blob | File) | null;
    first_name?: string;
    last_name?: string;
    is_active?: boolean;
};

export type Folder = {
    readonly id: string;
    readonly updated: string;
    updated_by: CustomUser;
    readonly tags: Array<string>;
    parent: ParentFolder;
    readonly created: string;
    inherit_permissions?: boolean;
    name: string;
    description?: string | null;
    favorite?: boolean;
    readonly polymorphic_ctype: number | null;
};

export type FolderRequest = {
    parent: ParentFolderRequest;
    inherit_permissions?: boolean;
    name: string;
    description?: string | null;
    favorite?: boolean;
};

export type FolderTyped = {
    resourcetype: string;
} & Folder;

export type Invoice = {
    readonly id: string;
    readonly updated: string;
    updated_by: CustomUser;
    readonly tags: Array<string>;
    readonly line_items: Array<LineItem>;
    parent: ParentFolder;
    readonly created: string;
    inherit_permissions?: boolean;
    name: string;
    description?: string | null;
    total?: number | null;
    readonly polymorphic_ctype: number | null;
};

export type InvoiceRequest = {
    parent: ParentFolderRequest;
    inherit_permissions?: boolean;
    name: string;
    description?: string | null;
    total?: number | null;
};

export type InvoiceTyped = {
    resourcetype: string;
} & Invoice;

export type Item = {
    readonly id: string;
    readonly updated: string;
    updated_by: CustomUser;
    readonly tags: Array<string>;
    name?: string | null;
    value?: number | null;
    line_item: string;
};

export type ItemRequest = {
    name?: string | null;
    value?: number | null;
    line_item: string;
};

export type Kit = {
    readonly id: string;
    readonly updated: string;
    updated_by: CustomUser;
    readonly tags: Array<string>;
    parent: ParentFolder;
    readonly created: string;
    inherit_permissions?: boolean;
    name: string;
    polymorphic_ctype: Nested;
    start: Nested;
};

export type KitRequest = {
    parent: ParentFolderRequest;
    inherit_permissions?: boolean;
    name: string;
};

export type KitTyped = {
    resourcetype: string;
} & Kit;

export type LineItem = {
    readonly id: string;
    readonly updated: string;
    updated_by: CustomUser;
    readonly tags: Array<string>;
    readonly items: Array<Item>;
    position?: number | null;
    invoice: string;
};

export type LineItemRequest = {
    position?: number | null;
    invoice: string;
};

export type Nested = {
    readonly id: string;
    name: string;
    hidden?: boolean;
    parent?: string | null;
};

export type NestedRequest = {
    app_label: string;
    model: string;
};

export type NodePolymorphic = ({
    resourcetype?: 'Folder';
} & FolderTyped) | ({
    resourcetype?: 'Invoice';
} & InvoiceTyped) | ({
    resourcetype?: 'Kit';
} & KitTyped);

/**
 * A ModelSerializer that takes an additional `fields` argument that
 * controls which fields should be displayed.
 */
export type Organization = {
    readonly id: string;
    name: string;
    avatar?: string | null;
    root: Nested;
};

/**
 * A ModelSerializer that takes an additional `fields` argument that
 * controls which fields should be displayed.
 */
export type OrganizationRequest = {
    name: string;
    avatar?: (Blob | File) | null;
};

export type PaginatedAnswerList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<Answer>;
};

export type PaginatedCustomUserList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<CustomUser>;
};

export type PaginatedFolderList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<Folder>;
};

export type PaginatedInvoiceList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<Invoice>;
};

export type PaginatedItemList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<Item>;
};

export type PaginatedKitList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<Kit>;
};

export type PaginatedLineItemList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<LineItem>;
};

export type PaginatedNodePolymorphicList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<NodePolymorphic>;
};

export type PaginatedOrganizationList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<Organization>;
};

export type PaginatedQuestionList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<Question>;
};

export type ParentFolder = {
    readonly id: string;
    name: string;
};

export type ParentFolderRequest = {
    name: string;
};

export type PatchedAnswerRequest = {
    inherit_permissions?: boolean;
    title?: string;
    description?: string;
    image?: string | null;
    index?: number;
    parent?: string | null;
};

/**
 * A ModelSerializer that takes an additional `fields` argument that
 * controls which fields should be displayed.
 */
export type PatchedCustomUserRequest = {
    email?: string;
    avatar?: (Blob | File) | null;
    first_name?: string;
    last_name?: string;
    is_active?: boolean;
};

export type PatchedFolderRequest = {
    parent?: ParentFolderRequest;
    inherit_permissions?: boolean;
    name?: string;
    description?: string | null;
    favorite?: boolean;
};

export type PatchedInvoiceRequest = {
    parent?: ParentFolderRequest;
    inherit_permissions?: boolean;
    name?: string;
    description?: string | null;
    total?: number | null;
};

export type PatchedItemRequest = {
    name?: string | null;
    value?: number | null;
    line_item?: string;
};

export type PatchedKitRequest = {
    parent?: ParentFolderRequest;
    inherit_permissions?: boolean;
    name?: string;
};

export type PatchedLineItemRequest = {
    position?: number | null;
    invoice?: string;
};

/**
 * A ModelSerializer that takes an additional `fields` argument that
 * controls which fields should be displayed.
 */
export type PatchedOrganizationRequest = {
    name?: string;
    avatar?: (Blob | File) | null;
};

export type PatchedQuestionRequest = {
    inherit_permissions?: boolean;
    title?: string;
    description?: string | null;
    image?: string | null;
};

export type Question = {
    readonly id: string;
    readonly updated: string;
    updated_by: CustomUser;
    readonly tags: Array<string>;
    readonly created: string;
    inherit_permissions?: boolean;
    title?: string;
    description?: string | null;
    image?: string | null;
    polymorphic_ctype: Nested;
    parent: Nested;
    next: Nested;
    readonly answers: Array<Nested>;
};

export type QuestionRequest = {
    inherit_permissions?: boolean;
    title?: string;
    description?: string | null;
    image?: string | null;
};

export type AnswersListData = {
    body?: never;
    path?: never;
    query?: {
        created?: string;
        created__gte?: string;
        created__lte?: string;
        description?: string;
        description__contains?: string;
        description__exact?: string;
        id?: string;
        id__exact?: string;
        id__in?: string;
        image?: string;
        index?: number;
        inherit_permissions?: boolean;
        name__contains?: string;
        name__exact?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        parent?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        polymorphic_ctype?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
        title?: string;
        updated?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/answers/';
};

export type AnswersListResponses = {
    200: PaginatedAnswerList;
};

export type AnswersListResponse = AnswersListResponses[keyof AnswersListResponses];

export type AnswersCreateData = {
    body: AnswerRequest;
    path?: never;
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/answers/';
};

export type AnswersCreateResponses = {
    201: Answer;
};

export type AnswersCreateResponse = AnswersCreateResponses[keyof AnswersCreateResponses];

export type AnswersDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this answer.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/answers/{id}/';
};

export type AnswersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AnswersDestroyResponse = AnswersDestroyResponses[keyof AnswersDestroyResponses];

export type AnswersRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this answer.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/answers/{id}/';
};

export type AnswersRetrieveResponses = {
    200: Answer;
};

export type AnswersRetrieveResponse = AnswersRetrieveResponses[keyof AnswersRetrieveResponses];

export type AnswersPartialUpdateData = {
    body?: PatchedAnswerRequest;
    path: {
        /**
         * A UUID string identifying this answer.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/answers/{id}/';
};

export type AnswersPartialUpdateResponses = {
    200: Answer;
};

export type AnswersPartialUpdateResponse = AnswersPartialUpdateResponses[keyof AnswersPartialUpdateResponses];

export type AnswersUpdateData = {
    body: AnswerRequest;
    path: {
        /**
         * A UUID string identifying this answer.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/answers/{id}/';
};

export type AnswersUpdateResponses = {
    200: Answer;
};

export type AnswersUpdateResponse = AnswersUpdateResponses[keyof AnswersUpdateResponses];

export type DocumentsListData = {
    body?: never;
    path?: never;
    query?: {
        created?: string;
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id?: string;
        id__exact?: string;
        id__in?: string;
        inherit_permissions?: boolean;
        name__contains?: string;
        name__exact?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        parent?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        polymorphic_ctype?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
        updated?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/documents/';
};

export type DocumentsListResponses = {
    200: PaginatedNodePolymorphicList;
};

export type DocumentsListResponse = DocumentsListResponses[keyof DocumentsListResponses];

export type FoldersListData = {
    body?: never;
    path?: never;
    query?: {
        created?: string;
        created__gte?: string;
        created__lte?: string;
        description?: string;
        description__contains?: string;
        description__exact?: string;
        favorite?: string;
        id?: string;
        id__exact?: string;
        id__in?: string;
        inherit_permissions?: boolean;
        name?: string;
        name__contains?: string;
        name__exact?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        parent?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        polymorphic_ctype?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
        updated?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/folders/';
};

export type FoldersListResponses = {
    200: PaginatedFolderList;
};

export type FoldersListResponse = FoldersListResponses[keyof FoldersListResponses];

export type FoldersCreateData = {
    body: FolderRequest;
    path?: never;
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        favorite?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/folders/';
};

export type FoldersCreateResponses = {
    201: Folder;
};

export type FoldersCreateResponse = FoldersCreateResponses[keyof FoldersCreateResponses];

export type FoldersDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this folder.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        favorite?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/folders/{id}/';
};

export type FoldersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type FoldersDestroyResponse = FoldersDestroyResponses[keyof FoldersDestroyResponses];

export type FoldersRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this folder.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        favorite?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/folders/{id}/';
};

export type FoldersRetrieveResponses = {
    200: Folder;
};

export type FoldersRetrieveResponse = FoldersRetrieveResponses[keyof FoldersRetrieveResponses];

export type FoldersPartialUpdateData = {
    body?: PatchedFolderRequest;
    path: {
        /**
         * A UUID string identifying this folder.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        favorite?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/folders/{id}/';
};

export type FoldersPartialUpdateResponses = {
    200: Folder;
};

export type FoldersPartialUpdateResponse = FoldersPartialUpdateResponses[keyof FoldersPartialUpdateResponses];

export type FoldersUpdateData = {
    body: FolderRequest;
    path: {
        /**
         * A UUID string identifying this folder.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        favorite?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/folders/{id}/';
};

export type FoldersUpdateResponses = {
    200: Folder;
};

export type FoldersUpdateResponse = FoldersUpdateResponses[keyof FoldersUpdateResponses];

export type InvoicesListData = {
    body?: never;
    path?: never;
    query?: {
        created?: string;
        created__gte?: string;
        created__lte?: string;
        description?: string;
        description__contains?: string;
        description__exact?: string;
        id?: string;
        id__exact?: string;
        id__in?: string;
        inherit_permissions?: boolean;
        name?: string;
        name__contains?: string;
        name__exact?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        parent?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        polymorphic_ctype?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
        total?: number;
        updated?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/invoices/';
};

export type InvoicesListResponses = {
    200: PaginatedInvoiceList;
};

export type InvoicesListResponse = InvoicesListResponses[keyof InvoicesListResponses];

export type InvoicesCreateData = {
    body: InvoiceRequest;
    path?: never;
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/invoices/';
};

export type InvoicesCreateResponses = {
    201: Invoice;
};

export type InvoicesCreateResponse = InvoicesCreateResponses[keyof InvoicesCreateResponses];

export type InvoicesDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this invoice.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/invoices/{id}/';
};

export type InvoicesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type InvoicesDestroyResponse = InvoicesDestroyResponses[keyof InvoicesDestroyResponses];

export type InvoicesRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this invoice.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/invoices/{id}/';
};

export type InvoicesRetrieveResponses = {
    200: Invoice;
};

export type InvoicesRetrieveResponse = InvoicesRetrieveResponses[keyof InvoicesRetrieveResponses];

export type InvoicesPartialUpdateData = {
    body?: PatchedInvoiceRequest;
    path: {
        /**
         * A UUID string identifying this invoice.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/invoices/{id}/';
};

export type InvoicesPartialUpdateResponses = {
    200: Invoice;
};

export type InvoicesPartialUpdateResponse = InvoicesPartialUpdateResponses[keyof InvoicesPartialUpdateResponses];

export type InvoicesUpdateData = {
    body: InvoiceRequest;
    path: {
        /**
         * A UUID string identifying this invoice.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/invoices/{id}/';
};

export type InvoicesUpdateResponses = {
    200: Invoice;
};

export type InvoicesUpdateResponse = InvoicesUpdateResponses[keyof InvoicesUpdateResponses];

export type ItemsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/items/';
};

export type ItemsListResponses = {
    200: PaginatedItemList;
};

export type ItemsListResponse = ItemsListResponses[keyof ItemsListResponses];

export type ItemsCreateData = {
    body: ItemRequest;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type ItemsCreateResponses = {
    201: Item;
};

export type ItemsCreateResponse = ItemsCreateResponses[keyof ItemsCreateResponses];

export type ItemsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this item.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}/';
};

export type ItemsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ItemsDestroyResponse = ItemsDestroyResponses[keyof ItemsDestroyResponses];

export type ItemsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this item.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}/';
};

export type ItemsRetrieveResponses = {
    200: Item;
};

export type ItemsRetrieveResponse = ItemsRetrieveResponses[keyof ItemsRetrieveResponses];

export type ItemsPartialUpdateData = {
    body?: PatchedItemRequest;
    path: {
        /**
         * A UUID string identifying this item.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}/';
};

export type ItemsPartialUpdateResponses = {
    200: Item;
};

export type ItemsPartialUpdateResponse = ItemsPartialUpdateResponses[keyof ItemsPartialUpdateResponses];

export type ItemsUpdateData = {
    body: ItemRequest;
    path: {
        /**
         * A UUID string identifying this item.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}/';
};

export type ItemsUpdateResponses = {
    200: Item;
};

export type ItemsUpdateResponse = ItemsUpdateResponses[keyof ItemsUpdateResponses];

export type KitsListData = {
    body?: never;
    path?: never;
    query?: {
        created?: string;
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id?: string;
        id__exact?: string;
        id__in?: string;
        inherit_permissions?: boolean;
        name?: string;
        name__contains?: string;
        name__exact?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        parent?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        polymorphic_ctype?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
        start?: string;
        updated?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/kits/';
};

export type KitsListResponses = {
    200: PaginatedKitList;
};

export type KitsListResponse = KitsListResponses[keyof KitsListResponses];

export type KitsCreateData = {
    body: KitRequest;
    path?: never;
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/kits/';
};

export type KitsCreateResponses = {
    201: Kit;
};

export type KitsCreateResponse = KitsCreateResponses[keyof KitsCreateResponses];

export type KitsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this kit.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/kits/{id}/';
};

export type KitsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type KitsDestroyResponse = KitsDestroyResponses[keyof KitsDestroyResponses];

export type KitsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this kit.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/kits/{id}/';
};

export type KitsRetrieveResponses = {
    200: Kit;
};

export type KitsRetrieveResponse = KitsRetrieveResponses[keyof KitsRetrieveResponses];

export type KitsPartialUpdateData = {
    body?: PatchedKitRequest;
    path: {
        /**
         * A UUID string identifying this kit.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/kits/{id}/';
};

export type KitsPartialUpdateResponses = {
    200: Kit;
};

export type KitsPartialUpdateResponse = KitsPartialUpdateResponses[keyof KitsPartialUpdateResponses];

export type KitsUpdateData = {
    body: KitRequest;
    path: {
        /**
         * A UUID string identifying this kit.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/kits/{id}/';
};

export type KitsUpdateResponses = {
    200: Kit;
};

export type KitsUpdateResponse = KitsUpdateResponses[keyof KitsUpdateResponses];

export type LineitemsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/lineitems/';
};

export type LineitemsListResponses = {
    200: PaginatedLineItemList;
};

export type LineitemsListResponse = LineitemsListResponses[keyof LineitemsListResponses];

export type LineitemsCreateData = {
    body: LineItemRequest;
    path?: never;
    query?: never;
    url: '/api/v1/lineitems/';
};

export type LineitemsCreateResponses = {
    201: LineItem;
};

export type LineitemsCreateResponse = LineitemsCreateResponses[keyof LineitemsCreateResponses];

export type LineitemsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this line item.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/lineitems/{id}/';
};

export type LineitemsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type LineitemsDestroyResponse = LineitemsDestroyResponses[keyof LineitemsDestroyResponses];

export type LineitemsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this line item.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/lineitems/{id}/';
};

export type LineitemsRetrieveResponses = {
    200: LineItem;
};

export type LineitemsRetrieveResponse = LineitemsRetrieveResponses[keyof LineitemsRetrieveResponses];

export type LineitemsPartialUpdateData = {
    body?: PatchedLineItemRequest;
    path: {
        /**
         * A UUID string identifying this line item.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/lineitems/{id}/';
};

export type LineitemsPartialUpdateResponses = {
    200: LineItem;
};

export type LineitemsPartialUpdateResponse = LineitemsPartialUpdateResponses[keyof LineitemsPartialUpdateResponses];

export type LineitemsUpdateData = {
    body: LineItemRequest;
    path: {
        /**
         * A UUID string identifying this line item.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/lineitems/{id}/';
};

export type LineitemsUpdateResponses = {
    200: LineItem;
};

export type LineitemsUpdateResponse = LineitemsUpdateResponses[keyof LineitemsUpdateResponses];

export type OrganizationsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/organizations/';
};

export type OrganizationsListResponses = {
    200: PaginatedOrganizationList;
};

export type OrganizationsListResponse = OrganizationsListResponses[keyof OrganizationsListResponses];

export type OrganizationsCreateData = {
    body: OrganizationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/';
};

export type OrganizationsCreateResponses = {
    201: Organization;
};

export type OrganizationsCreateResponse = OrganizationsCreateResponses[keyof OrganizationsCreateResponses];

export type OrganizationsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OrganizationsDestroyResponse = OrganizationsDestroyResponses[keyof OrganizationsDestroyResponses];

export type OrganizationsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsRetrieveResponses = {
    200: Organization;
};

export type OrganizationsRetrieveResponse = OrganizationsRetrieveResponses[keyof OrganizationsRetrieveResponses];

export type OrganizationsPartialUpdateData = {
    body?: PatchedOrganizationRequest;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsPartialUpdateResponses = {
    200: Organization;
};

export type OrganizationsPartialUpdateResponse = OrganizationsPartialUpdateResponses[keyof OrganizationsPartialUpdateResponses];

export type OrganizationsUpdateData = {
    body: OrganizationRequest;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsUpdateResponses = {
    200: Organization;
};

export type OrganizationsUpdateResponse = OrganizationsUpdateResponses[keyof OrganizationsUpdateResponses];

export type QuestionsListData = {
    body?: never;
    path?: never;
    query?: {
        answers?: Array<string>;
        created?: string;
        created__gte?: string;
        created__lte?: string;
        description?: string;
        description__contains?: string;
        description__exact?: string;
        id?: string;
        id__exact?: string;
        id__in?: string;
        image?: string;
        inherit_permissions?: boolean;
        name__contains?: string;
        name__exact?: string;
        next?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        parent?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        polymorphic_ctype?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
        title?: string;
        updated?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/questions/';
};

export type QuestionsListResponses = {
    200: PaginatedQuestionList;
};

export type QuestionsListResponse = QuestionsListResponses[keyof QuestionsListResponses];

export type QuestionsCreateData = {
    body?: QuestionRequest;
    path?: never;
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/questions/';
};

export type QuestionsCreateResponses = {
    201: Question;
};

export type QuestionsCreateResponse = QuestionsCreateResponses[keyof QuestionsCreateResponses];

export type QuestionsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this question.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/questions/{id}/';
};

export type QuestionsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type QuestionsDestroyResponse = QuestionsDestroyResponses[keyof QuestionsDestroyResponses];

export type QuestionsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this question.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/questions/{id}/';
};

export type QuestionsRetrieveResponses = {
    200: Question;
};

export type QuestionsRetrieveResponse = QuestionsRetrieveResponses[keyof QuestionsRetrieveResponses];

export type QuestionsPartialUpdateData = {
    body?: PatchedQuestionRequest;
    path: {
        /**
         * A UUID string identifying this question.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/questions/{id}/';
};

export type QuestionsPartialUpdateResponses = {
    200: Question;
};

export type QuestionsPartialUpdateResponse = QuestionsPartialUpdateResponses[keyof QuestionsPartialUpdateResponses];

export type QuestionsUpdateData = {
    body?: QuestionRequest;
    path: {
        /**
         * A UUID string identifying this question.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/questions/{id}/';
};

export type QuestionsUpdateResponses = {
    200: Question;
};

export type QuestionsUpdateResponse = QuestionsUpdateResponses[keyof QuestionsUpdateResponses];

export type UsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/users/';
};

export type UsersListResponses = {
    200: PaginatedCustomUserList;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersCreateData = {
    body: CustomUserRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateResponses = {
    201: CustomUser;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}/';
};

export type UsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersDestroyResponse = UsersDestroyResponses[keyof UsersDestroyResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: CustomUser;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedCustomUserRequest;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}/';
};

export type UsersPartialUpdateResponses = {
    200: CustomUser;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: CustomUserRequest;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}/';
};

export type UsersUpdateResponses = {
    200: CustomUser;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/';
};

export type UsersMeRetrieveResponses = {
    200: CustomUser;
};

export type UsersMeRetrieveResponse = UsersMeRetrieveResponses[keyof UsersMeRetrieveResponses];