# Generated by Django 5.1.4 on 2025-02-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_lineitem_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="position",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
